const SORT_NAME_ON = 'sortFilter/SORT_NAME/ON';
const SORT_NAME_OFF = 'sortFilter/SORT_NAME/OFF';
const TOGGLE_SORT_BY_AZ = 'sortFilter/TOGGLE_SORT_BY_AZ';

const FILTER_BY_CATEGORY_ALL = 'sortFilter/FILTER_BY_CATEGORY_ALL';
const FILTER_BY_CATEGORY = 'sortFilter/FILTER_BY_CATEGORY';

export default {
  SORT_NAME_ON,
  SORT_NAME_OFF,
  TOGGLE_SORT_BY_AZ,
  FILTER_BY_CATEGORY_ALL,
  FILTER_BY_CATEGORY
}
