const FETCH_LOCATIONS = 'locations/FETCH_LOCATIONS';
const FETCH_LOCATIONS_COMPLETED = 'locations/FETCH_LOCATIONS/COMPLETED';
const LOAD_LOCATIONS = 'locations/LOAD_LOCATIONS';

const SELECT_LOCATION = 'locations/SELECT_LOCATION';
const UNSELECT_LOCATION = 'locations/UNSELECT_LOCATION';

const OPEN_MODAL_EDIT = 'locations/OPEN_MODAL/EDIT';
const OPEN_MODAL_NEW = 'locations/OPEN_MODAL/NEW';
const CLOSE_MODAL = 'locations/CLOSE_MODAL';

const MODAL_FIELD_NAME_CHANGE = 'locations/MODAL/NAME/CHANGE';
const MODAL_FIELD_NAME_ERROR = 'locations/MODAL/NAME/ERROR';

const MODAL_FIELD_CATEGORY_CHANGE = 'locations/MODAL/CATEGORY/CHANGE';

const MODAL_FIELD_COORDIN_CHANGE = 'locations/MODAL/COORDIN/CHANGE';

const MODAL_FIELD_ADDRESS = 'locations/MODAL/ADDRESS/UPDATE';

const ADD_LOCATION = 'locations/ADD_LOCATION';
const EDIT_LOCATION = 'locations/EDIT_LOCATION';
const REMOVE_LOCATION = 'locations/REMOVE_LOCATION';

export default {
  FETCH_LOCATIONS,
  FETCH_LOCATIONS_COMPLETED,
  LOAD_LOCATIONS,
  SELECT_LOCATION,
  UNSELECT_LOCATION,
  OPEN_MODAL_EDIT,
  OPEN_MODAL_NEW,
  CLOSE_MODAL,
  MODAL_FIELD_NAME_CHANGE,
  MODAL_FIELD_NAME_ERROR,
  MODAL_FIELD_CATEGORY_CHANGE,
  MODAL_FIELD_COORDIN_CHANGE,
  MODAL_FIELD_ADDRESS,
  ADD_LOCATION,
  EDIT_LOCATION,
  REMOVE_LOCATION
}
