const FETCH_CATEGORIES = 'categories/FETCH_CATEGORIES';
const FETCH_CATEGORIES_COMPLETED = 'categories/FETCH_CATEGORIES/COMPLETED';
const LOAD_CATEGORIES = 'categories/LOAD_CATEGORIES';

const SELECT_CATEGORY = 'categories/SELECT_CATEGORY';
const UNSELECT_CATEGORY = 'categories/UNSELECT_CATEGORY';

const OPEN_MODAL_EDIT = 'categories/OPEN_MODAL/EDIT';
const OPEN_MODAL_NEW = 'categories/OPEN_MODAL/NEW';
const CLOSE_MODAL = 'categories/CLOSE_MODAL';

const EDIT_SUBMIT = 'categories/EDIT_SUBMIT';
const ADD_NEW_CATEGORY = 'categories/ADD_NEW_CATEGORY';
const REMOVE_CATEGORY = 'categories/REMOVE_CATEGORY';

const MODAL_FIELD_NAME_CHANGE = 'categories/MODAL/NAME/CHANGE';
const MODAL_FIELD_NAME_ERROR = 'categories/MODAL/NAME/ERROR';

export default {
  FETCH_CATEGORIES,
  FETCH_CATEGORIES_COMPLETED,
  LOAD_CATEGORIES,
  SELECT_CATEGORY,
  UNSELECT_CATEGORY,
  REMOVE_CATEGORY,
  OPEN_MODAL_NEW,
  OPEN_MODAL_EDIT,
  CLOSE_MODAL,
  MODAL_FIELD_NAME_CHANGE,
  MODAL_FIELD_NAME_ERROR,
  EDIT_SUBMIT,
  ADD_NEW_CATEGORY
}
